        !COMPILER-GENERATED INTERFACE MODULE: Sat Feb 04 20:38:22 2012
        MODULE FOUCO__genmod
          INTERFACE 
            SUBROUTINE FOUCO
            END SUBROUTINE FOUCO
          END INTERFACE 
        END MODULE FOUCO__genmod
