        !COMPILER-GENERATED INTERFACE MODULE: Sat Feb 04 20:33:10 2012
        MODULE INT_TO_STRING4__genmod
          INTERFACE 
            SUBROUTINE INT_TO_STRING4(NUMBER,STRING)
              INTEGER(KIND=4), INTENT(IN) :: NUMBER
              CHARACTER(LEN=4), INTENT(OUT) :: STRING
            END SUBROUTINE INT_TO_STRING4
          END INTERFACE 
        END MODULE INT_TO_STRING4__genmod
