        !COMPILER-GENERATED INTERFACE MODULE: Sat Feb 04 20:32:16 2012
        MODULE SET_FILENAME__genmod
          INTERFACE 
            SUBROUTINE SET_FILENAME(ROOTDIR,COSXOIN,FILENAME)
              CHARACTER(LEN=20), INTENT(IN) :: ROOTDIR
              REAL(KIND=8), INTENT(IN) :: COSXOIN
              CHARACTER(LEN=150) :: FILENAME
            END SUBROUTINE SET_FILENAME
          END INTERFACE 
        END MODULE SET_FILENAME__genmod
