#!/bin/bash

rm Cyrano
cd fortran_sources/MAXW/
mpif90 -pg -mcmodel=medium -O2 -fno-automatic -fdefault-real-8 -fdefault-double-8 -ffixed-line-length-132 -I../COMMONS/ -o Cyrano.exe *.f
cp -v Cyrano.exe ../../Cyrano
cd ../../
exit 0